[package]
name = "dark-dbc-token-2022-processor-test"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dev-dependencies]
curve25519-dalek = "=4.1.3"
solana-account-info = "=2.3.0"
solana-pubkey = "=2.4.0"
solana-rent = "=2.2.1"
solana-sdk-ids = "=2.2.1"
solana-sysvar = { version = "=2.3.0", features = ["bincode"] }
solana-zk-sdk = "=7.0.1"
solana-zk-sdk-token = { package = "solana-zk-sdk", version = "=2.3.13" }
spl-token-2022 = { version = "=9.0.0", features = ["no-entrypoint"] }

[profile.dev]
debug = 0

[profile.test]
debug = 0