[package]
name = "launch-shield-proof-runner"
version = "0.1.0"
edition = "2021"
default-run = "launch-shield-proof-runner"

[[bin]]
name = "launch-shield-proof-runner"
path = "src/main.rs"
required-features = ["sp1-executor"]

[features]
sp1-executor = ["dep:sp1-sdk"]
sp1-prover = ["sp1-executor", "dep:hex", "sp1-sdk/native-gnark"]
sp1-network = ["sp1-executor", "dep:hex", "sp1-sdk/network"]

[[bin]]
name = "launch-shield-vkey"
path = "src/bin/vkey.rs"
required-features = ["sp1-executor"]

[[bin]]
name = "launch-shield-prove"
path = "src/bin/prove.rs"
required-features = ["sp1-prover"]

[[bin]]
name = "launch-shield-prove-network"
path = "src/bin/prove_network.rs"
required-features = ["sp1-network"]

[dependencies]
launch-shield-proof-relation = { path = "../relation" }
hex = { version = "=0.4.3", optional = true }
sp1-sdk = { version = "=6.8.1", default-features = false, features = ["blocking"], optional = true }

[build-dependencies]
sp1-build = "=6.8.1"